#ifndef NEW_KERNELS_CUH
#define NEW_KERNELS_CUH

#define MAX_ACC_HALF2 2048.0 // 1024 ??
#define MAX_ACC_SHORT 25000 //TODO which value here ???

#include <thrust/iterator/counting_iterator.h>

#include "kernelhelpers.cuh" //must be included before the kernels

#include "half2_kernels.cuh"
#include "dpx_s16_kernels.cuh"
#include "dpx_s32_kernels.cuh"
#include "float_kernels.cuh"

#include "util.cuh"
#include "config.hpp"

namespace cudasw4{

//extern template instantiations

//ScoreOutputIterator
using ScoreIterInst = TopNMaximaArray; 
//using ScoreIterInst = float*; 
//PositionsIterator
using PosIterInst = decltype(thrust::make_counting_iterator<ReferenceIdT>(0));

//half2_kernel_instantiations.cu
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 2, 24, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 4, 16, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 8, 10, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 8, 12, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 8, 14, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 8, 16, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 8, 18, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 8, 20, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 8, 22, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 8, 24, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 8, 26, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 8, 28, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 8, 30, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 8, 32, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 16, 18, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 16, 20, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 16, 22, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 16, 24, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 16, 26, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 16, 28, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 16, 30, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 16, 32, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 32, 18, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 32, 20, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 32, 22, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 32, 24, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 32, 26, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 32, 28, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 32, 30, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 32, 32, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 32, 34, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 32, 36, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 32, 38, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_Protein_single_pass_half2_new<256, 32, 40, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);

extern template void call_NW_local_affine_Protein_many_pass_half2_new<256, 32, 22, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, __half2*, __half2*, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);



//float_kernel_instantiations.cu

extern template void call_NW_local_affine_read4_float_query_Protein_new<2, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<3, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<4, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<5, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<6, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<7, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<8, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<9, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<10, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<11, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<12, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<13, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<14, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<15, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<16, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<18, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<20, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<22, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<24, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<26, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<28, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<30, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<32, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<34, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<36, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<38, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);
extern template void call_NW_local_affine_read4_float_query_Protein_new<40, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, float2 * const, float2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const float, const float, cudaStream_t);

extern template void call_launch_process_overflow_alignments_kernel_NW_local_affine_read4_float_query_Protein_new<20, ScoreIterInst, ReferenceIdT*>(const int* const, float2* const, const size_t, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, ReferenceIdT* const, const char4* const, const SequenceLengthT, const float, const float, cudaStream_t);



//dpx_s32_kernel_instantiations.cu

extern template void call_NW_local_affine_s32_DPX_new<2, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<3, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<4, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<5, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<6, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<7, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<8, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<9, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<10, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<11, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<12, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<13, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<14, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<15, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<16, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<18, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<20, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<22, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<24, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<26, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<28, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<30, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<32, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<34, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<36, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<38, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);
extern template void call_NW_local_affine_s32_DPX_new<40, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, int2 * const, int2 * const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, const char4*, const SequenceLengthT, const int, const int, cudaStream_t);

extern template void call_launch_process_overflow_alignments_kernel_NW_local_affine_s32_DPX_new<20, ScoreIterInst, ReferenceIdT*>(const int* const, int2* const, const size_t, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, ReferenceIdT* const, const char4* const, const SequenceLengthT, const int, const int, cudaStream_t);



//dpx_s16_kernel_instantiations.cu
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 2, 24, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 4, 16, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 8, 10, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 8, 12, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 8, 14, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 8, 16, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 8, 18, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 8, 20, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 8, 22, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 8, 24, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 8, 26, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 8, 28, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 8, 30, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 8, 32, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 16, 18, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 16, 20, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 16, 22, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 16, 24, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 16, 26, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 16, 28, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 16, 30, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 16, 32, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 32, 18, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 32, 20, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 32, 22, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 32, 24, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 32, 26, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 32, 28, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 32, 30, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 32, 32, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 32, 34, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 32, 36, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 32, 38, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);
extern template void call_NW_local_affine_single_pass_s16_DPX_new<256, 32, 40, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);

extern template void call_NW_local_affine_many_pass_s16_DPX_new<256, 32, 22, ScoreIterInst, PosIterInst>(BlosumType, const char * const, ScoreIterInst const, short2*, short2*, const size_t* const, const SequenceLengthT* const, PosIterInst const, const int, ReferenceIdT* const, int* const, const bool, const char4*, const SequenceLengthT, const short, const short, cudaStream_t);


} //namespace cudasw4

#endif